### ISSUE TITLE
Less assertive implementation with more user-friendly feedback 

### ISSUE THREAD

**Issue by lexmag** [lexmag/dicon#2]

**Comment by whatyouhide** [comment]
First steps in d332c3293fe05e4eb03d885cd0309205b27dd14f, which introduces friendlier error messages for the command-line arguments in Mix tasks.

**Comment by whatyouhide** [comment]
Closing this after https://github.com/lexmag/dicon/pull/7 has been merged. The problem now is not that we're too assertive: we now give good feedback when something bad happens (errors). We should still take care of giving some feedback for when things go as planned though (i.e., #3).
