### ISSUE TITLE
SSH connection timing out too soon

### ISSUE THREAD

**Issue by whatyouhide** [lexmag/dicon#9]
```
** (MatchError) no match of right hand side value: {:error, :timeout}
```

This can happen because it takes time to stop the running application (`dicon.control stop`) or whatever, I think we need a longer timeout for a start.

**Comment by b0oh** [comment]
+1

**Comment by whatyouhide** [comment]
The SSH timeouts (read, write, execute) are now configurable through the `Dicon.SecureShell` configuration.
